const fullSongs = {
   "00-PIU XX": [
        "1601 - SHK - Wedding Crashers",
        "1602 - SHK - Switronic",
        "1603 - ATAS - Obliteration",
        "1604 - ATAS - Transacaglia in G-minor",
        "1605 - SLAM - 1949",
        "1607 - MAX - JANUS",
        "1608 - MAX - I Want U",
        "1609 - MAX - District 1",
        "1615 - nato - Nyarlathotep",
        "1616 - nato - HEART RABBIT COASTER",
        "1617 - Nato - Lepton Strike",
        "1618 - Doin - Skeptic",
        "1619 - Doin - Iolite Sky",
        "1620 - Pory - (Percent X)",
        "1621 - Pory - La Cinquantaine",
        "1622 - KIEN - Le Grand Rouge",
        "1623 - StaticSphere & FUGU SUISAN - CARMEN BUS",
        "1624 - HyuN - Macaron Day",
        "1625 - Fiverwater - Ice of Death",
        "1626 - Quree - Poseidon",
        "1627 - QWertism - Adrenaline Blaster",
        "1628 - Applesoda - VANISH",
        "1629 - Applesoda - Tales of Pumpnia",
        "1630 - Garlic Squad - Kimchi Fingers",
        "1631 - DM Ashura - Orbit Stabilizer",
        "1632 - KURORAK - DESTRUCIMATE",
        "1633 - Jehezukiel - Clematis Rapsodia",
        "1634 - D_AAN - Wicked Legend",
        "1635 - Memme - Tantanmen",
        "1636 - Cashew - Stardream (feat. Romelon)",
        "16A0 - Sr. Lan Belmont - Can-can ~Orpheus in The Party Mix~",
        "16A1 - Yakikaze & Cashew - Papasito (feat. KuTiNA)",
        "16A2 - Jehezukiel - Fires of Destiny",
        "16A3 - MonstDeath - The End of the World ft. Skizzo",
        "16A4 - WyvernP - Forgotten Vampire",
        "16D0 - Applesoda vs MAX - Desaparecer",
        "16D1 - SUNNY && DOIN - ERRORCODE 0",
        "16D3 - Paul Bazooka - Meteo5cience (GADGET mix)",
        "16D5 - Memme - Fire Noodle Challenge",
        "16F0 - Nato - Nyarlathotep - SHORT CUT -",
        "16F1 - SHK - Wedding Crashers - SHORT CUT -",
        "16F2 - Sr. Lan Belmont - Can-can ~Orpheus in The Party Mix~ - SHORT CUT -",
        "16F3 - MAX - XX OPENING - SHORT CUT -",
        "16F4 - MAX - I Want U - SHORT CUT -",
        "16F5 - Quree - Poseidon - SHORT CUT -",
        "16F6 - SHK - Switronic - SHORT CUT -",
        "1641 - LUCY - Jogging",
        "1642 - HAON, PULLIK - The Little Prince (Prod. Godic)",
        "1643 - Dreamcatcher - Full Moon",
        "1644 - HIGHTEEN - Timing",
        "1645 - Dreamcatcher - Fly high",
        "1646 - Turbo - Black Cat",
        "1647 - (G)I-DLE - HANN (Alone)",
        "1648 - CHUNG HA - Snapping",
        "1649 - PRODUCE48 - NEKKOYA (PICK ME)",
        "1650 - APink - I'm so sick",
        "1651 - Wanna one - BOOMERANG",
        "1652 - SUNMI - Gashina",
        "1653 - EVERGLOW - Adios",
        "1654 - SEVENTEEN - HIT",
        "1655 - MOMOLAND - BBoom BBoom",
        "1656 - N.Flying - Rooftop",
        "1657 - OH MY GIRL - BUNGEE (Fall in Love)",
        "1658 - MAMAMOO - Starry Night",
        "1659 - iKON - LOVE SCENARIO",
        "1660 - GFRIEND - Time for the moon night",
        "1661 - EVERBLOW - Bon Bon Chocolat",
        "1662 - SEVENTEEN - VERY NICE",
        "1663 - HONG JINYOUNG - GOOD BYE",
        "1664 - Dreamcatcher - YOU AND I",
        "1665 - Norazo - King of Sales",
        "1666 - CHUNG HA - Gotta Go",
        "1667 - HAON - Boong Boong (Feat. Sik-K) (Prod. GroovyRoom)",
        "16D8 - (G)I-DLE - HANN (Alone) - FULL SONG -",
        "16D9 -  PRODUCE48 - NEKKOYA (PICK ME) - FULL SONG -",
        "16E0 - MOMOLAND - BBoom BBoom - FULL SONG-",
        "16E1 - APink - I'm so sick - FULL SONG -",
        "16E3 - SUNMI - Gashina - FULL SONG -",
        "16E4 - MAMAMOO - Starry Night - FULL SONG -",
        "16E5 - GFRIEND - Time for the moon night - FULL SONG -",
        "16E7 - SEVENTEEN - VERY NICE - FULL SONG -",
        "16E8 - HONG JINYOUNG - GOOD BYE - FULL SONG -",
        "1668 - Matduke - Club Night",
        "1669 - Matduke - Indestructible",
        "1670 - DASU - 8 6",
        "1671 - HyuN feat. Syepias - CROSS SOUL",
        "1672 - Quree - Broken Karma (PIU EDIT)",
        "1673 - TOTO - After a thousand years",
        "1674 - Yassi Pressman - Lala",
        "1675 - D_AAN - F(R)IEND",
        "1676 - Siromaru + Cranky - Conflict",
        "1677 - Cranky - Danger & Danger",
        "1694 - Nato - Nihilism - Another Ver. -",
        "1695 - Cranky - Phalanx RS2018 edit",
        "1696 - SYNTHWULF - POINT ZERO 2",
        "16C5 - DM Ashura - Allegro con Fuoco - FULL SONG -",
        "16D4 - Cashew - Prime Time",
        "16F7 - DASU - 8 6 - FULL SONG -",
        "16F8 - Zircon - Baroque Virus - FULL SONG -",
        "1678 - SHK - Imagination",
        "1679 - zeron - Black Swan",
        "1680 - ESTi x M2U - Obelisque",
        "1681 - MAX - Rage of Fire",
        "1682 - Nato & r300k - Dual Racing RED vs BLUE",
        "1683 - Yamajet - Cycling",
        "1684 - Memme - Uranium",
        "1685 - FE - Xeroize",
        "1686 - M2U - Rising Star",
        "1687 - Memme - Cutie Song",
        "1688 - r300k - Headless Chicken",
        "1689 - Yamajet - Over The Horizon",
        "1690 - Lotze - Loki",
        "1691 - Lunatic Sounds - Dement ~After Legend~",
        "1692 - Houseplan - Houseplan",
        "1693 - Roy Mikelate - Your Mind",
    ],
    "01-FULL SONGS": [
        "13C0 - [Full Song] Step",
        "13C1 - [Full Song] I'm The Best",
        "13C2 - [Full Song] Shanghai Romance",
        "13C3 - [Full Song] Fantastic Baby",
        "13C4 - [Full Song] Can't Nobody",
        "13C5 - [Full Song] Heart Breaker",
        "13C7 - [Full Song] Crayon",
        "C08F - [Full Song] Emergency",
        "C15F - [Full Song] Mr. Fire Fighter",
        "E10F - [Full Song] A.U Ready",
        "E15F - [Full Song] You Fall in Me",
        "E51 - [Full Song] Guitar Man",
        "E53 - [Full Song] Monkey Fingers",
        "E56 - [Full Song] Astral Song",
        "E58 - [Full Song] No Despair",
        "E70 - [Full Song] It's My Business",
        "E71 - [Full Song] Very Old Couples",
        "E72 - [Full Song] Come Back Home",
        "E73 - [Full Song] Feel The Soul",
        "E74 - [Full Song] V.I.P",
        "E75 - [Full Song] A Maelstrom",
        "E76 - [Full Song] Fly",
        "E77 - [Full Song] Tell Me",
        "PE392 - [Full Song] Z -The New Legend-",
        "14C2 - [Full Song] NoNoNo",
        "B09F - [Full Song] Typhoon",
        "B13F - [Full Song] I'll Give You All My Love",
        "B51 - [Full Song] Dignity",
        "B57 - [Full Song] Canon-D",
        "D08F - [Full Song] Free",
        "D11F - [Full Song] For You",
        "D38 - [Full Song] U Inside My Dim Memory",
        "D39 - [Full Song] Fire (Banya)",
        "D40 - [Full Song] Lovely",
        "D41 - [Full Song] Love is a Danger Zone 2",
        "D42 - [Full Song] Beat of the War 2",
        "D43 - [Full Song] Hold the Line",
        "1042 - [Full Song] Deja Vu",
        "1043 - [Full Song] Narcisista por excelencia",
        "1044 - [Full Song] Dawn of the Apocalypse",
        "1045 - [Full Song] Fire",
        "1046 - [Full Song] Wanna",
        "1135 - [Full Song] Interference",
        "1136 - [Full Song] Magic Girl",
        "1137 - [Full Song] Ring Ding Dong",
        "1138 - [Full Song] Shock",
        "1139 - [Full Song] Energy",
        "1140 - [Full Song] Like a Man",
        "1141 - [Full Song] No.3",
        "1142 - [Full Song] Crash Day",
        "1143 - [Full Song] Hot Issue",
        "14C0 - [Full Song] Bar Bar Bar",
        "14C1 - [Full Song] Sugar Free",
        "14C4 - Kara - Pandora Full Song",
        "14C5 - [Full Song] Four Seasons of Loneliness ver.B",
        "14C6 - [Full Song] Bad Apple!! (feat. Nomico)",
        "14C7 Creed - 1st Desire -",
        "Crowdpleaser",
        "F50 - [Full Song] Chopsticks Challenge",
        "F51 - [Full Song] LaLaLa",
        "F52 - [Full Song] Adios",
        "F53 - [Full Song] Panuelito Rojo",
        "F54 - [Full Song] Procedimientos Para Llegar A Un Comun Acuerdo",
        "F55 - [Full Song] Forward",
        "F56 - [Full Song] Slightly",
        "F57 - [Full Song] Come!",
        "F58 - [Full Song] Chocolate",
        "F59 - [Full Song] Digan Lo Que Digan",
        "F60 - [Full Song] Trato de no Trabarme",
        "F61 - [Full Song] Crazy",
        "F62 - [Full Song] U",
        "F63 - [Full Song] Change Myself",
        "F64 - [Full Song] Enter The Dragon",
        "F65 - [Full Song] Beat # No. 4",
        "INF - [Full Song] Haven",
        "INF - [Full Song] Maslo",
        "INF - [Full Song] Smells Like a Chocolate",
        "INF - [Full Song] Star Command",
        "INF Baroque Virus",
        "INF Blow Full Song",
        "INF Don't Bother Me Full Song",
        "INF Funky Tonight Full Song",
        "INF Gargoyle Full Song",
        "INF Pop The Track Full Song",
        "INF The Ark Sailing Over Truth",
        "INF Vospi - Nervous full song",
        "INF We Are Full",
        "INF electric"
    ],
    "02-REMIX": [
        "13A0 - [Remix] BIG to the BANG",
        "13A1 - [Remix] Super Mackerel",
        "13A2 - [Remix] Infinity RMX",
        "13A3 - [Remix] What Are You Doin",
        "322 - [Remix] 3rd O.B.G Diva Remix",
        "323 - [Remix] Park Mee Kyung Remix",
        "325 - [Remix] Park Jin Young Remix",
        "924 - [Remix] EXTRA Hip-Hop Remix",
        "925 - [Remix] E-Pak-Sa Remix",
        "926 - [Remix] EXTRA Disco Remix",
        "927 - [Remix] EXTRA Deux Remix",
        "928 - [Remix] EXTRA BanYa Remix",
        "C41 - [Remix] Love Is A Danger Zone - Try To B.P.M",
        "C42 - [Remix] Zero K Hip-Hop Mix",
        "C43 - [Remix] Zero K House Mix",
        "C44 (327) - [Remix] Banya Hard Remix",
        "E100 - [Remix] Final Audition 3 & Chimera Remix",
        "E50 - [Remix] Banya P-Guitar Remix",
        "E52 - [Remix] Money Fingers",
        "E54 - [Remix] NX2 K-pop Remix 1",
        "E55 - [Remix] NX2 Hip Hop Remix",
        "E57 - [Remix] NX2 K-Pop Remix 2",
        "E59 - [Remix] NX2 K-Pop Remix 3",
        "E60 - [Remix] NX2 Diva Remix",
        "E61 - [Remix] Chopstix & Dance Vibrations Remix",
        "E63 - [Remix] May Remix",
        "E64 - [Remix] Red Remix",
        "EF921 - [Remix] Mr. Firefighter & Beat of The War 2 Remix",
        "219 - [Remix] Jo Sung Mo Remix",
        "220 - [Remix] Uhm Jung Hwa Remix",
        "223 - [Remix] SM Town Remix",
        "224 - [Remix] Repeatorment Remix",
        "B26 - [Remix] Novarash Remix",
        "B27 - [Remix] Lexy & 1TYM Remix",
        "B28 - [Remix] Tream Vook of the War",
        "B29 - [Remix] Banya Classic Remix",
        "B30 - [Remix] Deux Remix",
        "B31 - [Remix] Diva's Remix",
        "B50 - [Remix] The World Remix",
        "B52 (326) - [Remix] Novasonic Remix",
        "B53 (119) - [Remix] Turbo Remix",
        "B54 (225) - [Remix] 2nd Hidden Remix",
        "B55 (221) - [Remix] Drunken Family Remix",
        "B56 - [Remix] Banya Hip Hop Remix",
        "D31 - [Remix] K-Pop Dance",
        "D32 - [Remix] Groove Party",
        "D33 - [Remix] Pop House Mix",
        "D34 - [Remix] Wi-Ex-Doc-Va",
        "D35 - [Remix] Bemera",
        "D36 - [Remix] Banya-P Classic Mix",
        "D37 - [Remix] Chicago Club Mix",
        "E101 - [Remix] Yasangma",
        "116 - [Remix] 1st Diva Remix",
        "117 - [Remix] 1st Disco Remix",
        "118 - [Remix] 1st Techno Remix",
        "120 - [Remix] 1st Battle HipHop",
        "121 - [Remix] 1st Battle Disco",
        "122 - [Remix] 1st Battle Techno",
        "123 - [Remix] 1st Battle Hardcore",
        "415 - [Remix] Sechskies Remix",
        "1031 - [Remix] Banya-P Classic Remix",
        "1032 - [Remix] K-Pop Mix (Old & New)",
        "1033 - [Remix] Papa Helloizing",
        "1034 - [Remix] Banya-P Classic Remix 2",
        "1035 - [Remix] Hard Core Rock Mix",
        "1036 - [Remix] Pro Pop Mix",
        "1037 - [Remix] Set Up Me 2 Mix",
        "1038 - [Remix] msgoon RMX pt.5",
        "1039 - [Remix] msgoon RMX pt.6",
        "1040 - [Remix] msgoon RMX pt.7",
        "1041 - [Remix] History - We are the ZEST",
        "1047 - [Remix] Pump it Up With You",
        "1129 - [Remix] K-Pop Girl Group RMX",
        "1130 - [Remix] K-Pop Boy Group RMX",
        "1131 - [Remix] Vacuum Cleaner",
        "1132 - [Remix] Everybody Got 2 Know",
        "1133 - [Remix] The Historic Classic Remix A",
        "1134 - [Remix] The Historic Classic Remix B",
        "14A0 - [Remix] Beethoven Influenza",
        "14A1 - [Remix] Avalanquiem",
        "14A2 - [Remix] Paradoxx",
        "Armakitten",
        "Blowin it Up",
        "F30 - [Remix] 45rpm & Eun Ji Won Mix",
        "F31 - [Remix] The People Didn't Know ''Pumping Up''",
        "F32 - [Remix] Ugly Duck Toccata",
        "F33 - [Remix] Caprice of DJ Otada",
        "F34 - [Remix] Dr. KOA",
        "F35 - [Remix] Jam O Beat #no 4",
        "F36 - [Remix] YG Remix",
        "F37 - [Remix] Nina Pxndx Mix",
        "F38 - [Remix] Big Metra Remix",
        "F39 - [Remix] NXA Hip Hop Mix",
        "F40 - [Remix] Novasonic Mix Ver. 3",
        "F41 - [Remix] Mr. Fire Figther Falls In Love With Me",
        "F42 - [Remix] J Knows That Old Bong",
        "F43 - [Remix] Turkey Virus",
        "F44 - [Remix] Msgoon RMX Pt.1",
        "F45 - [Remix] Msgoon RMX Pt.2",
        "F46 - [Remix] Msgoon RMX Pt.3",
        "F47 (F72) - [Remix] msgoon RMX Pt.4",
        "F70 - [Remix] Yasangma 2",
        "F71 - [Remix] Scream Song",
    ],
    "03-SHORT CUT": [
        "13E0 - [Short Cut] Pop The Track",
        "13E1 - [Short Cut] Passacaglia",
        "13E2 - [Short Cut] Ignis Fatuus",
        "13E3 - [Short Cut] Flew Far Faster",
        "13E4 - [Short Cut] Unique",
        "13E5 - [Short Cut] U Got Me Rocking",
        "14F0 - [Short Cut] Heavy Rotation (cover)",
        "1048 - [Short Cut] Final Audition 2",
        "1049 - [Short Cut] Final Audition 3",
        "1050 - [Short Cut] Final Audition Episode 2-X",
        "1051 - [Short Cut] Love is a Danger Zone",
        "1052 - [Short Cut] Love is a Danger Zone 2",
        "1053 - [Short Cut] Extravaganza",
        "1054 - [Short Cut] Chiken Wing",
        "1055 - [Short Cut] Winter",
        "1056 - [Short Cut] Solitary 2",
        "1057 - [Short Cut] Moonlight",
        "1058 - [Short Cut] Witch Doctor",
        "1059 - [Short Cut] Exceed 2 Opening",
        "1060 - [Short Cut] NX Opening",
        "1061 - [Short Cut] K.O.A. Alice in Wonderworld",
        "1062 - [Short Cut] Beemera",
        "1063 - [Short Cut] Pumptris 8bit Ver",
        "1064 - [Short Cut] Destination",
        "1065 - [Short Cut] Procedimientos Para Llegar a un Comum Acuerdo",
        "1145 - [Short Cut] Trotpris",
        "1146 - [Short Cut] Cleaner",
        "1147 - [Short Cut] Take Out",
        "1148 - [Short Cut] Overblow",
        "1149 - [Short Cut] X-Rave",
        "14E0 - [Short Cut] Super Fantasy",
        "14E1 - [Short Cut] Yog Sothoth",
        "14E2 - [Short Cut] Silhouette Effect",
        "14E3 - [Short Cut] Selfishness",
        "14E4 - [Short Cut] Rock The House",
        "14E5 - [Short Cut] Move That Body!",
        "14E6 - [Short Cut] Prime Opening",
        "14E7 - [Short Cut] Stardust Overdrive",
        "Beat the Ghost",
        "Bullfighter's Song",
        "Dance On Fire",
        "Dance Vibration",
        "Energizer",
        "Enhanced Reality",
        "Guitar Man",
        "Incubator",
        "Kill Them",
        "What Happen",
    ],
    "06-PRO~PRO2": [
        "!",
        "Accelerator",
        "Aliens in Our Midst",
        "All of the World",
        "Allegro Con Fuoco",
        "Anubis",
        "Art City",
        "Back in Boogie Town",
        "Bang the Bass",
        "Be Alive (Raaban Inc. Mix)",
        "Be My Friend",
        "Beyond the Sky",
        "Blow My Mind",
        "Boogie Land",
        "Boom Digi Da",
        "Boulafacet",
        "Breathing You In",
        "Chaotic WHITE",
        "Chopstix",
        "Clockwork Genesis",
        "Closer to Heaven",
        "Coalesce",
        "Coming Out",
        "Concerto",
        "Cosmic Unconsciousness",
        "Cowgirl",
        "Crowdpleaser (Drop the Mic Mix)",
        "DJ Superstar",
        "Dabbi Doo",
        "Dance Vibrations",
        "Dance all Night",
        "Dawgs In Da House",
        "Dawn (Perpetual Mix)",
        "Deadbeat Boyfriend",
        "Destiny",
        "Disco Punks on Jolt",
        "Do What You Wanna Do",
        "Don't Don't Go Away",
        "Dream To Nightmare",
        "Elder God Shrine",
        "Electrock",
        "Energizer",
        "Epilogue",
        "Esperanza",
        "Esperanza (The Trinity)",
        "EternuS",
        "Euphoria",
        "Exotica",
        "Feels Just Like That Night",
        "Frozen",
        "Funk Factory",
        "Gargoyle",
        "Go! (EK Mix)",
        "Groovin' Motion",
        "Hanky Panky",
        "HardKore of The North",
        "Hardkore Atomic",
        "Hasse Mich",
        "Haven",
        "Heel and Toe",
        "Hell Flame",
        "I Think I Like That Sound",
        "I'm Just a DJ",
        "Ika Uka",
        "In The Groove",
        "In the Night",
        "Incognito",
        "Infection",
        "Into My Dream (Kaveh Azizi Remix)",
        "It's Over Now",
        "July -Euromix-",
        "King of the Beats",
        "Kitty Cat",
        "Ladybug",
        "Lolitabot",
        "London Bridge",
        "Love Eternal",
        "Man vs Mountain",
        "Maslo",
        "Memory",
        "Mind Your Matter",
        "Mission Incredible",
        "Monolith",
        "Moonstone",
        "Move It Groove It",
        "Necromancy",
        "Nightmoves",
        "Oasis",
        "Oh Oh Oh Sexy Vampire",
        "One Step Higher",
        "Online",
        "Operator",
        "Photosynthesis",
        "Pink Fuzzy Bunnies",
        "Playa D'Embossa",
        "Poco Loco",
        "Power Trip",
        "Ra",
        "Radius",
        "Rainspark",
        "Rave Until The Night Is Over (C.T.M.)",
        "Rave Until The Night is Over",
        "Re-Rave",
        "Riders, Unite!",
        "Right Back Up",
        "Rippin' It Up",
        "Robotix",
        "Robotix (The Trinity)",
        "Rock Robotic",
        "Rockhill",
        "Round and Round",
        "STOP! & Go",
        "Shine (Breakz Mix)",
        "Shooting Star",
        "Smart Optics",
        "Smells Like a Chocolate",
        "Span",
        "Star Command",
        "Step on It",
        "Style On My Speed Dial",
        "Summer (Speedy Mix)",
        "Sunshine",
        "Supremacy",
        "Sweet Senorita",
        "Swing Baby Swing",
        "Swing the House",
        "Switchback",
        "Take Me Back",
        "Take My Time",
        "Tell Me A Story (Compendium Mix)",
        "Tension",
        "Terminal",
        "The Game of Love",
        "The Last Firstborn",
        "The Neon Underground",
        "The Next Step",
        "Tribal Style",
        "Tribe Attacker",
        "UFO Catcher",
        "Unlikely (Stay With Me)",
        "Utopia",
        "Utopia (The Trinity)",
        "VVV",
        "Virtual Emotion",
        "Wake Up",
        "Wanting You",
        "We Are Loud",
        "Wham Bam Boogie",
        "What Happened",
        "While Tha Rekkid Spinz",
        "Who",
        "X-Rave",
        "Xuxa",
        "Y2Z",
        "You Bring the Rain",
        "Zodiac",
        "Zodiac (The Trinity)"
    ],
    "07-INFINITY": [
        "Baroque Virus - Zircon",
        "Black Maria",
        "Blow",
        "Bubblegum Dancer (J-Mi & Midi-D Remix)",
        "Creatures ov Deception",
        "Dance (The Way ot Moves)",
        "Devil's Spirit",
        "Dragonfly",
        "Electric",
        "Elise - DM Ashura",
        "Ethereality",
        "Euphorium",
        "Extravaganza Reborn",
        "Fallen Angel",
        "Fresh",
        "Hypnosis (Synthwulf Mix)",
        "Ignis Fatuus",
        "Invincible",
        "Last Day Alive - sanxion7",
        "Love is a Danger Zone (Cranky Mix)",
        "Maniac - DM Ashura",
        "Moonshard - Triple Star",
        "Nervous",
        "Party 4U (Holy Nite Mix)",
        "Passacaglia",
        "Pop the Track",
        "Shadows",
        "Solitary Sanxion 7 Mix",
        "The Ark Sailing Over Truth",
        "The Best is Gonna Get",
        "The Fool",
        "The Revolution",
        "The trident ov power",
        "True",
        "Venetian Staccato",
    ],
    "08-1ST~PERFECT": [
        "301 - Final Audition 2",
        "302 - Naissance",
        "303 - Turkey March",
        "304 - With my Lover",
        "305 - An Interesting View",
        "306 - Nightmare",
        "307 - Close Your Eyes",
        "308 - Free Style",
        "309 - Midnight Blue",
        "310 - She Likes Pizza",
        "311 - Pumping Up",
        "312 - Don't Bother Me",
        "313 - Love Song",
        "314 - Lovers Grief",
        "315 - To the Top",
        "316 - Separation With Her",
        "317 - Puyo Puyo",
        "318 - We Are",
        "319 - Time to Say Goodbye",
        "320 - Tell Me (Jinusean)",
        "321 - Ok Ok (Beauty and the Beast)",
        "201 - Creamy Skinny",
        "202 - Hate",
        "203 - Koul",
        "204 - Final Audition",
        "205 - Extravaganza",
        "206 - Rewind",
        "207 - I-Yah!",
        "208 - Fighting Spirits",
        "210 - Love (S.E.S)",
        "211 - Please",
        "212 - Com' Back",
        "213 - Mobius Strip",
        "214 - Fever",
        "215 - Curiosity",
        "216 - Love (Click-B)",
        "217 - Tell Me Tell Me",
        "218 - Heart Break",
        "101 - Ignition Starts",
        "102 - Hypnosis",
        "103 - Forever Love",
        "104 - Passion",
        "105 - Black Cat",
        "106 - Pom Pom Pom",
        "107 - The Rap",
        "108 - Come to Me (Clon)",
        "109 - Funky Tonight",
        "110 - What Do U Really Want",
        "111 - Hatred",
        "112 - Another Truth",
        "113 - I Want U",
        "114 - I Dont Know Anything",
        "115 - No Particular Reason",
        "501 - Pump Jump",
        "502 - N",
        "503 - Rolling Christmas",
        "504 - All I Want For X-Mas",
        "505 - Beethoven Virus",
        "506 - I Will Accept You",
        "507 - Come Back to Me",
        "508 - As I Told U",
        "509 - I Know",
        "510 - My Fantasy",
        "511 - Unforgettable Memory",
        "512 - Hayuga",
        "513 - Certain Victory",
        "514 - Ultramania",
        "515 - Bonaccia",
        "516 - Slam",
        "517 - Space Fantasy",
        "401 - Oh! Rosa",
        "402 - First Love",
        "403 - Betrayer",
        "404 - Solitary",
        "405 - Mr. Larpus",
        "406 - Sad Salsa",
        "407 - Summer of Love",
        "408 - Kiss",
        "409 - Man & Woman",
        "410 - First Love (Clon)",
        "411 - A Trap",
        "412 - Disco Bus",
        "413 - Run!",
        "414 - Run to You"
    ],
    "10-EXTRA~PREX 3": [
        "801 - Bambole",
        "802 - Bee",
        "803 - Burning Krypt",
        "804 - Can You Feel Dis or Dat",
        "805 - Clap Your Hands",
        "806 - Conga",
        "807 - D Gang",
        "808 - DJ Nightmare",
        "809 - Eres Para Mi",
        "810 - Fiest A Macarena Pt.1",
        "811 - Hello",
        "812 - On Your Side",
        "813 - Everybody",
        "814 - Join the Party",
        "815 - Lay it Down",
        "816 - Let the Sunshine",
        "817 - Lovething",
        "818 - Mexi Mexi",
        "819 - You Don't Wanna Runup",
        "820 - Beat of the War",
        "821 - Empire of the Sun",
        "822 - Just a Girl",
        "823 - Let's Get the Party Started",
        "824 - Objection",
        "825 - It's my Party",
        "826 - Come to Me",
        "827 - Music",
        "828 - Master of Puppets",
        "901 - Flower of the Night",
        "902 - Circus Magic",
        "903 - Move Your Head",
        "904 - Trash Man",
        "905 - Funky Jockey",
        "906 - Starian",
        "907 - Big Money",
        "908 - Wayo Wayo",
        "909 - Mistake",
        "910 - The Rap Act 3",
        "911 - Chicken Wing",
        "912 - Holiday",
        "913 - Radezky Can Can",
        "914 - Wish You Could Find",
        "915 - Loner",
        "916 - Monkey Magic",
        "917 - Out of the Ring",
        "918 - Blind Faith",
        "919 - Lazenca Save Us",
        "920 - Ferry Boat",
        "921 - Pierrot",
        "922 - Final Audition Episode 1",
        "923 - First Love (Techno Mix)",
        "601 - Oops! I Did It Again",
        "602 - Bye Bye Bye",
        "603 - I Need to Know",
        "604 - Let's Get Loud",
        "605 - Mambo No. 5",
        "606 - Take On Me",
        "607 - A Cerca",
        "608 - De Volta ao Planeta",
        "609 - Pensamento",
        "610 - Popozuda Rock'n Roll",
        "611 - Rebola na Boa",
        "612 - Sempre Assim",
        "613 - Uma Bomba",
        "614 - Vaqueiro Bom Demais",
        "701 - Dr. M",
        "702 - Emperor",
        "703 - Get Your Groove On",
        "704 - Love is a Danger Zone",
        "705 - Maria",
        "706 - Mission Possible",
        "707 - My Way",
        "708 - Point Break",
        "709 - Street Show Down",
        "710 - Top City",
        "711 - Winter",
        "712 - Will O The Wisp",
        "713 - Till The End of Time",
        "714 - Oy Oy Oy",
        "715 - We Will Meet Again",
        "716 - Miss's Story",
        "717 - Set Me Up",
        "718 - Dance With Me",
        "719 - Go Away",
        "720 - I Love You",
        "721 - Gotta be Kidding",
        "722 - Zzanga",
        "723 - A Prison Without Bars",
        "724 - A Whistle",
        "725 - Gentleman Quality",
        "726 - Run Away",
        "727 - Swing Baby",
        "728 - Temptation",
        "729 - Y",
        "730 - Perfect!",
        "731 - Let's Boogie",
        "732 - My Best Day is Gone",
        "733 - The Waves",
        "734 - Always",
        "735 - Vook",
        "736 - Csikos Post"
    ],
    "100-Challenge": [
        '16F8 - Zircon - Baroque Virus - FULL SONG -',
        '1044 - [Full Song] Dawn of the Apocalypse',
        '1135 - [Full Song] Interference',
        '1142 - [Full Song] Crash Day',
        'F60 - [Full Song] Trato de no Trabarme',
        'INF Gargoyle Full Song',
        'INF The Ark Sailing Over Truth',
        'Point Zero 2 Full Song',
    ],
    "11-EXCEED~ZERO": [
        "C01 - Beat of the War 2",
        "C02 - Moonlight",
        "C02A - Moonlight (Original Ver.)",
        "C03 - Witch Doctor",
        "C03A - Witch Docva",
        "C04 - Love is a Danger Zone 2",
        "C05 - Phantom",
        "C05A - Phantom (Speedup Ver.)",
        "C06 - Papa Gonzales",
        "C07 - Jump",
        "C08 - Emergency",
        "C09 - My Friend",
        "C10 - Wuthering Heights",
        "C11 - Do It Yourself",
        "C12 - What's Goin On",
        "C13 - All Famy",
        "C14 - Chung Hwa Ban Jeom",
        "C15 - Mr. Fire Fighter",
        "C16 - Footprints",
        "C17 - Oh My!",
        "C18 - Enter the Dragon",
        "C19 - Storm",
        "C1C01 - Beat of the War 2 (Another)",
        "C20 - Turn Around",
        "C21 - I Love You Baby",
        "C22 - Up Up",
        "DC04 - Love is a Danger Zone 2 (Another)",
        "B01 - Greenhorn",
        "B02 - Hot",
        "B03 - Pray",
        "B04 - Go Away",
        "B05 - Drunken in Melody",
        "B06 - Deja Vu",
        "B07 - U",
        "B08 - Lion's Roar",
        "B09 - Typhoon",
        "B10 - Eternity",
        "B11 - Foxy Lady",
        "B12 - Too Late",
        "B13 - I'll Give You All My Love",
        "B14 - Huu Yah Yeah",
        "B15 - We Don't Stop",
        "B16 - J Bong",
        "B17 - Hi-Bi",
        "B18 - Solitary 2",
        "B19 - Canon-D",
        "B20 - Le Code de Bonne Conduite",
        "A01 - Final Audition 3 U.F",
        "A02 - Naissance 2",
        "A03 - Monkey Fingers",
        "A04 - Blazing",
        "A05 - Pump Me Amadeus",
        "A06 - X-tream",
        "A07 - Get Up",
        "A08 - Dignity",
        "A09 - Shake That Bootie",
        "A10 - Valenti",
        "A11 - What Do You Really Want",
        "A12 - Go",
        "A13 - Flamenco",
        "A14 - Kiss Me",
        "A15 - Essa Maneira",
        "A16 - Ba Be Loo Be Ra",
        "A17 - La Cubanita",
        "A18 - Shake it Up",
        "A19 - One Love",
        "A20 - Power of Dreams",
        "A21 - Watch Out",
        "A22 - Fiesta",
        "A23 - Soca Make Yuh Ram Ram",
        "A24 - Born to be Alive",
        "A25 - Xibom Bombom",
        "A26 - Oh! Rosa (Spanish ver.)",
        "A27 - First Love (Spanish ver.)",
        "AE01 - A Little Less Conversation",
        "AE03 - Let's Groove",
        "AE04 - Name of the Game",
        "AE05 - Rapper's Delight",
        "AE06 - Walkie Talkie Man",
    ],
    "12-NX~NXA": [
        "E01 - Solitary 1.5",
        "E02 - Beat the Ghost",
        "E03 - Caprice of Otada",
        "E04 - Money",
        "E05 - Monkey Fingers 2",
        "E06 - Nice to Meet You",
        "E07 - Very Old Couples",
        "E08 - Get My Phone Call",
        "E09 - Shiny Day",
        "E10 - A.U Ready",
        "E11 - V.I.P",
        "E12 - Faster Z",
        "E13 - Pumptris Quattro",
        "E14 - It's My Bussiness",
        "E15 - You Fall in Me",
        "E16 - A Maelstrom",
        "E17 - Astral Song",
        "E18 - No Despair",
        "E19 - Compunction",
        "E20 - Beat # No. 4",
        "E21 - Come Back Home",
        "E22 - Feel The Soul",
        "E23 - Guitar Man",
        "E24 - Higgledy Piggledy",
        "E25 - Jam O Beat",
        "E26 - Chopstix",
        "E27 - Dance all Night",
        "E28 - Dance Vibrations",
        "E29 - Energizer",
        "E30 - Groovin' Motion",
        "E31 - Tell Me",
        "E07A - Very Old Coulpes (Short Term Memory Version)",
        "E17A - Astral Song (Alternate Version)",
        "E18A - No Despair (Alternate Version)",
        "E20A - Beat # No. 4 (Alternate Version)",
        "D01 - Witch Doctor #1",
        "D02 - Arch of Darkness",
        "D03 - Chimera",
        "D04 - Go Back",
        "D05 - Fly",
        "D06 - One Night",
        "D07 - U Inside My Dim Memory",
        "D08 - Free!",
        "D09 - Lovely",
        "D10 - Terminal Depository",
        "D11 - For You",
        "D12 - Snow Dream",
        "D13 - Handsome Character That Pass",
        "D14 - 2006 Love Song",
        "D15 - Do You Know That -Old School-",
        "D16 - Gun Rock",
        "D17 - Bullfighting's Song",
        "D18 - Ugly Dee",
        "D19 - Hyun Jin Young Go Jin Young Go",
        "D20 - My Brother is Street Singer",
        "D21 - So",
        "D22 - Hold The Line",
        "D23 - It's The Hybs",
        "D24 - Throw'em Up",
        "D25 - Bust Back",
        "D26 - Haley",
        "D27 - We Goin' Fly Remix",
        "D28 - Final Audition Episode 2-1",
        "D29 - Fire (Banya)",
        "D30 - Final Audition Episode 2-2",
    ],
    "12-NX~NXA": [
        "E32 Fist of Fury",
        "F01 - Blaze Emotion",
        "F02 - Cannon X1",
        "F03 - Chopsticks Challenge",
        "F04 - La La La",
        "F05 - Adios",
        "F06 - Slightly",
        "F07 - I am Your Girl",
        "F08 - Only You",
        "F09 - Chocolate",
        "F10 - Forward",
        "F11 - Uprock",
        "F12 - Crazy",
        "F13 - Pañuelito Rojo",
        "F14 - Procedimientos para Llegar a un Comun Acuerdo",
        "F15 - Digan lo que Digan",
        "F16 - Pump Breakers",
        "F17 - Change Myself",
        "F18 - Come On!",
        "F19 - Bad Character",
        "F20 - U",
        "F21 - Breakin' Love",
        "F22 - The People didn't Know",
        "F23 - Dj Otada",
        "F24 - K.O.A. -Alice in Wonderworld-",
        "F25 - My Dreams",
        "F26 - Toccata",
        "F27 - Do it!",
        "F28 - Dawn of the Apocalypse",
        "F29 - Final Audition Episode 2-X",
        "F80 - In Your Fantasy",
        "FE13B - Pumptris 8Bit ver"
    ],
    "14-FIESTA~FIESTA 2": [
        "1228 - Dream To Nightmare",
        "1240 - VVV",
        "1301 - Pop The Track",
        "1303 - Passacaglia",
        "1304 - Baroque Virus",
        "1308 - Hypnosis (SynthWulf Mix)",
        "1309 - Flew Far Faster",
        "1310 - Unique",
        "1311 - Accident",
        "1312 - D",
        "1313 - U Got Me Rocking",
        "1314 - Lucid (PIU Edit)",
        "1315 - Nobody",
        "1316 - Bad Girl Good Girl",
        "1317 - Step",
        "1318 - I'm The Best",
        "1319 - Can't Nobody",
        "1320 - Shanghai Romance",
        "1321 - Fantastic Baby",
        "1322 - Lie",
        "1323 - Heart Breaker",
        "1324 - Hands Up (East4A Mix)",
        "1325 - Be Mine",
        "1326 - Crayon",
        "1327 - Mackerel",
        "1328 - Two Guys",
        "1329 - Danza Kuduro",
        "1330 - Rabiosa",
        "1331 - Lovumba",
        "1332 - One Two Three Go!",
        "1333 - Los Malaventurados No Lloran",
        "1334 - Sik Asik",
        "1335 - Online",
        "1336 - Dam",
        "1337 - Sugar Eyes",
        "1338 - Log-In",
        "1339 - Windmill",
        "1340 - Follow Me",
        "1341 - Yeo Rae A",
        "1390 - Mental Rider",
        "1201 - Monolith",
        "1202 - Y2Z",
        "1206 - Rockhill",
        "1208 - Switchback",
        "1209 - Ladybug",
        "1212 - HardKore of The North",
        "1218 - Rippin' It Up",
        "1219 - Tribe Attacker",
        "1221 - Virtual Emotion",
        "1222 - Take Me Back",
        "1225 - Re-Rave",
        "1226 - Heel and Toe",
        "1230 - Rainspark",
        "1235 - Utopia",
        "1236 - Xuxa",
        "1237 - Be Alive (Raaban Inc. Mix)",
        "1241 - Star Command"
    ],
    "14-FIESTA~FIESTA 2": [
        "1001 - X-Tree",
        "1002 - Sorceress Elise",
        "1003 - Betrayer -Act 2",
        "1004 - Good Life",
        "1005 - Big Beat",
        "1006 - Exciting",
        "1007 - By Chance",
        "1008 - U Got 2 Know",
        "1009 - To The Sky",
        "1010 - The Angel Who Lost Wings",
        "1011 - Innocent",
        "1012 - Enjoy! Enjoy!",
        "1013 - Destination",
        "1014 - Twist King",
        "1015 - Fire",
        "1016 - Wanna",
        "1017 - Vacuum",
        "1018 - Narcisista por Excelencia",
        "1019 - No Rhyme No Reason",
        "1020 - 80' Pop",
        "1021 - Do it Reggae Style",
        "1022 - Xenesis",
        "1023 - Arirang",
        "1024 - Tek -Club Copenhagen-",
        "1025 - Hello William",
        "1026 - Turkey March Minimal Tunes",
        "1027 - Get Up (And Go)",
        "1028 - Phantom -Intermezzo-",
        "1029 - Mission Possible -BlowBack-",
        "1030 - Pumping Jumping",
        "1094 - Tepris",
        "1095 - Napalm",
        "1096 - Dieciseis",
        "1101 - Cleaner",
        "1102 - Interference",
        "1103 - Reality",
        "1104 - Take Out",
        "1105 - Butterfly",
        "1106 - Overblow",
        "1107 - We Got 2 Know",
        "1108 - Magic",
        "1109 - Hot Issue",
        "1110 - Magic Girl",
        "1111 - Ring Ding Dong",
        "1112 - Shock",
        "1113 - Last Farewell",
        "1114 - Superman",
        "1115 - Energy",
        "1116 - Mother",
        "1117 - No.3",
        "1118 - Like a Man",
        "1119 - Crash Day",
        "1120 - What Happened",
        "1121 - Gargoyle",
        "1122 - Allegro Con Fuoco",
        "1123 - Hungarian Dance V",
        "1124 - The Devil",
        "1125 - X-Rave",
        "1126 - Native",
        "1127 - Smells Like a Chocolate",
        "1128 - Necromancy",
        "1150 - Hot issue (Alternate Version)",
        "1151 - Night Duty",
        "1152 - Pavane",
        "1153 - Pine Nut",
        "1154 - ASDF",
        "1155 - Last Farewell (Alternate Version)",
        "1156 - Says",
        "1157 - Energy (Alternate Version)",
        "1159 - Rave Until The Night is Over",
        "1160 - Jonathan's Dream",
        "1227 - Deadbeat Boyfriend"
    ],
    "17-PRIME": [
        "1410 - Requiem",
        "1411 - U Got Me Crazy",
        "1412 - B2",
        "1413 - Meteorize",
        "1414 - Mad5cience",
        "1415 - Hestia",
        "1416 - Amphitryon",
        "1417 - Leakage Voltage",
        "1418 - Removable Disk0",
        "1419 - Super Fantasy",
        "1420 - Violet Perfume",
        "1421 - Red Swan",
        "1422 - Hyacinth",
        "1423 - Blaze Emotion Band Version",
        "1424 - 1950",
        "1425 - Sugar Conspiracy Theory",
        "1426 - Allegro PIU Mosso",
        "1427 - Annihilator Method",
        "1428 - Move That Body",
        "1429 - Rock The House",
        "1430 - Scorpion King",
        "1431 - Point Zero One",
        "1433 - Red Snow",
        "1434 - Campanella",
        "1435 - You Again My Love",
        "1436 - Robot Battle",
        "1437 - Bar Bar Bar",
        "1438 - On and On",
        "1439 - Elvis",
        "1440 - Very Good",
        "1441 - I'm Sorry",
        "1442 - Pandora",
        "1443 - Venus",
        "1444 - Hate, Don't Hate!",
        "1445 - Supermagic",
        "1446 - Sugar Free",
        "1447 - Her",
        "1448 - NoNoNo",
        "1449 - Loner",
        "1450 - Flying Duck",
        "1451 - Ineffective Boss Without Power",
        "1452 - One",
        "1453 - The Revolution",
        "1454 - Selfishness",
        "1457 - Cosmical Rhythm",
        "1458 - Dolly Kiss",
        "1459 - Matador",
        "1460 - Milky Way Galaxy",
        "1461 - Feel My Happiness",
        "1462 - Ragnarok",
        "1463 - Achluoias",
        "1464 - Karyawisata",
        "1465 - Video out C",
        "1468 - Melodia",
        "1470 - Across the ocean",
        "1471 - Enhanced Reality",
        "1472 - Stardust Overdrive",
        "1473 - Reminiscence",
        "1474 - Moment Day",
        "1475 - Amai Yuuwaku Dangerous",
        "1476 - Yoropiku Pikuyoro!",
        "1477 - Imprinting",
        "1478 - Sudden Romance",
        "1479 - Mitotsudaira",
        "1480 - Smile Diary",
        "1481 - Bad Apple!! (Original Ver.)",
        "1481 - Bad Apple!! (feat. Nomico)",
        "1482 - 1st Desire feat Yu Oda",
        "1483 - Sora no Shirabe",
        "1484 - Four Seasons of Loneliness ver.B",
        "1485 - Ai Yurete",
        "1486 - Setsuna Trip",
        "1487 - Trashy Innocence",
        "1488 - Renai Yuusha",
        "1489 - After School Stride",
        "1490 - PRIME",
        "1491 - Bad End Night",
        "1492 - Queen of the Red",
        "1493 - Idealized Romance",
        "1494 - Just Hold On(To All Fingers)",
        "1495 - Unlock (cover)",
        "1496 - Heavy rotation",
        "1497 - Break It Down",
        "1498 - Hypercube",
        "1499 - Like Me",
        "1401 - Nemesis",
        "1402 - Katkoi",
        "1403 - Latino Virus",
        "1404 - Elysium",
        "1405 - Yog Sothoth",
        "1406 - Silhouette Effect",
        "1407 - Chinese Restaurant",
        "1408 - Avalanche",
        "1409 - Force of Ra",
        "1467 - Limbo",
        "1469 - Que viva la vida"
    ],
    "18-PRIME 2": [
        "1501 - Last Rebirth",
        "1502 - Super Capriccio",
        "1503 - Hellfire",
        "1504 - Tritium",
        "1505 - CROSS OVER",
        "1507 - God Mode feat. skizzo",
        "1508 - Shub Niggurath",
        "1509 - Further",
        "1510 - The Quick Brown Fox Jumps Over The Lazy Dog",
        "1511 - Silver Beat",
        "1512 - Bring Back the Beat",
        "1513 - Break Out",
        "1516 - Sarabande",
        "1517 - Kasou Shinja",
        "1518 - Overblow2",
        "1524 - Passing Rider",
        "1525 - Arcana Force",
        "1526 - Allegro Furioso",
        "1529 - Anguished Unmaking",
        "1530 - Utsushiyo No Kaze feat. Kana",
        "1533 - Hey U",
        "1536 - Twist Of Fate (feat.-Ruriling)",
        "1537 - HTTP",
        "1538 -  Up & Up",
        "1539 - Travel To Future",
        "1540 - Rave 'til the Earth's End",
        "1541 - Awakening",
        "1542 - ESCAPE",
        "1543 - Waltz Of Doge",
        "1544 - Bang Bang Bang",
        "1545 - Me Gustas Tu",
        "1546 - Rhythm Ta",
        "1547 - Chase Me",
        "1548 - Pick Me",
        "1549 - Jackpot",
        "1550 - Gotta Be You",
        "1551 - Boombayah",
        "1552 - SOBER",
        "1553 - Up & Down",
        "1554 - Good Night",
        "1555 - You're the Best",
        "1556 - Number Nine",
        "1557 - Acquaintance",
        "1559 - Energetic",
        "1560 - Beautiful",
        "1561 - PICK ME",
        "1562 - REALLY REALLY",
        "1564 - Moon Light Dance",
        "1575 - Step",
        "1576 - Just Kiddin",
        "1577 - Nakakapagpabagabag",
        "1578 - Heart Attack",
        "1584 - Hush",
        "1593 - V3",
        "1594 - Cross Time",
        "1595 - The Festival Ghost 2",
        "1597 - Helix",
        "1598 - Hyperion",
        "15A0 - Black Dragon",
        "15A1 - BSPower Explosion",
        "15A2 - Start On Red",
        "15A3 - Time Attack Blue",
        "15A4 - Magical Vacation",
        "15A5 - Visual Dream II (In Fiction)",
        "15A6 - Death Moon",
        "15A7 - Super Stylin'",
        "15A8 - Christmas Memories",
        "15A9 - Keep On!",
        "15B0 - Asterios -ReEnrty-",
        "15B1 - Le Grand Bleu",
        "15B2 - INFINITY",
        "15B3 - Gothique Resonance",
        "15B5 - BEDLAM",
        "15B6 - A Site De La Rue",
        "15B7 - Clue",
        "15B8 - Redline",
        "15B9 - Kill Them!",
        "15C0 - Donatello",
        "15C4 - Seize My Day",
        "15C5 - Fallen Angel",
        "15D0 - [Remix] Vulcan",
        "15D1 - [Remix] Shub Sothoth",
        "15D3 - [Remix] Leather",
        "15E0 - [Full Song] Me Gustas Tu",
        "15E1 - [Full Song] Bang Bang Bang",
        "15E2 - [Full Song] Boombayah",
        "15E3 - [Full Song] Up & Down",
        "15E4 - [Full Song] Acquaintance",
        "15E5 - [Full Song] Gargoyle",
        "15E6 - [Full Song] Hush",
        "15E7 - [Full Song] Chase Me",
        "15F0 - [Shortcut] Sarabande",
        "15F1 - [Shortcut] Death Moon",
        "15F3 - [Shortcut] PRIME 2 Opening",
        "15F4 - [Shortcut] Shub Niggurath",
        "15F5 - [Shortcut] Hyperion",
        "15F6 - [Shortcut] Kasou Shinja",
        "Nakakapagpabagabag Full Song",
        "Nato x Monstdeath - Lovecraft Remix"
    ],
    "20-M": [
        "16A7 - The reverie",
        "16B0 - Little Munchkin",
        "16B2 - Barber's Madness",
        "1700 - red blossom",
        "1701 - Festival of Death Moon",
        "1702 - GOD MODE 2.0",
        "1703 - ESP",
        "1704 - Autumn Break",
        "1705 - Ultimatum",
        "1706 - Highway Chaser",
        "1708 - Binary Star",
        "1709 - Bestest Frenemy!",
        "1710 - Lifestreaming",
        "1711 - NEVER GIVE UP!",
        "1712 - Dancing2Night",
        "1713 - 2STEP BABY",
        "1714 - Quantum Hyperspace",
        "1715 - New World",
        "1716 - Fairy Dash",
        "1717 - About the universe",
        "1718 - Kokugen Kairou Labirynth",
        "1719 - Perpetual",
        "1720 - Dancing",
        "1721 - Galaxy Collapse",
        "1725 - That Kitty (PIU Edit.)",
        "1726 - Underworld ft. Skizzo (PIU Edit.)",
        "1734 - 4NT",
        "1744 - Ultimate Eyes",
        "1746 - Dead Soul"
    ],
    "990-OVERCROSS": [
        "OW01A01 M2U[REX] - Heart of Witch",
        "OW01A02 M2U - Space of Soul",
        "OW01A04 M2U - Nodding Hawk",
        "OW01A07 BlackYooh vs Siromaru - BLACK or White",
        "OW01A09 TAK - Black Swan",
        "OW01A11 yak_won - SINUS",
        "OW01A12 yak_won - Wind Tales",
        "OW01A13 xi - Parousia",
        "OW01A14 Ginkiha - Oriens",
        "OW01A15 CYO Style - Heart Of Tokyo",
        "OW01A18 Sakuzyo - Imprinting",
        "OW01A21 LeaF - Alice in Misanthrope",
        "OW01A22 LeaF - Liliths Labyrinth",
        "OW01A23 LeaF - MARENOL",
        "OW01A26 ND Lee - In My Dream",
        "OW01A28 ESTi - OBLIVION",
        "OW01A30 NieN - Real Over Drive",
        "OW01A31 NieN - Only for You",
        "OW01A34 Paul Bazooka - Don_t Die",
        "OW01A37 Paul Bazooka - DrunkenStein",
        "OW01A42 team grimoire - C18H27NO3",
        "OW01A47 t+pazolite - Freedom Dive",
        "OW01A48 t+pazolite - QZKago Requiem",
        "OW01A49 t+pazolite - Oshama Scramble",
        "OW01A51 t+pazolite - strange Doll Play",
        "OW01A53 kobaryo- Bookmaker (2D Version)",
        "OW01A54 Kobaryo - Invisible Frenzy",
        "OW01A55 Kobaryo - Pumpin",
        "OW01A57 Freezer feat. Kiichigo - Berry Go!!",
        "OW01A59 Venstant - AriosoKiller",
        "OW01A60 MIDinco - Etude",
        "OW01A72 Tatsh - I.D",
        "OW01A73 Tatsh - Xepher",
        "OW01A74 siqlo - Yinmn Blue",
        "OW01A76 HyunN ft. Ms Valentine - Cross+Fate",
        "OW01A78 HyuN Feat Syepias - Cross+Soul",
        "OW01A79 HyuN feat. LyuU - Cross+Revolution",
        "OW01B01 Aran - Gate One",
        "OW01B02 M2U[REX] - Airwave",
        "OW01B03 Yuta Imai - Into The Madness",
        "OW01B04 DJ Genki - Avalon System",
        "OW01B06 Stephan F - Astronomia Fubuki CMT Bootleg Remix",
        "OW01B50 Topp Dogg - TopDog",
        "OW01B51 2NE1 - Crush",
        "OW01B71 Coconatsu - Pomegranate",
        "OW01C01 fripSide - Only my Railgun",
        "OW01C02 fripSide - Future Gazer",
        "OW01C03 fripSide - Level 5 Judgelight",
        "OW01C06 AVENEW f. Sakura Saori - Awayuki",
        "OW01C07 AVENEW f. Sakura Saori - Piste SMILE Nonstop",
        "OW01C11 Camellia Ft. Nanahira - Mofu Mofu After School",
        "OW01C13 Camellia ft. Nanahira - Ju-Ju- Yakiniku no Hi kara Phenix",
        "OW01C17 Naru Hakobe (MAO) - OutsideRRequieM",
        "OW01C23 HTT - Dont Say Lazy",
        "OW01C24 HTT - No Thank You",
        "OW01C27 Giga f. REOL - NO TITLE",
        "OW01C30 mcAT - Bomb A Head",
        "OW01C31 Azusa - Check My Soul",
        "OW01C32 minami - kawaki wo ameku",
        "OW01C34 Machico - Tomorrow",
        "OW01C37 MYTH & ROID - VORACITY",
        "OW01C39 MYTH & ROID - Crazy Scary Holy Fantasy (Chiptune version)",
        "OW01D01 Leaf - Aleph-0 Full Song",
        "OW01D02 Synthwulf - POINT ZERO TWO",
        "OW01D05 AVENEW f. Sakura Saori - Iris Full Song",
        "OW01D06 Kyary Pamyu Pamyu - Fashion Monster",
        "OW01D07 AVENEW f. Sakura Saori - Piste SMILE Non-stop!!",
        "OW01D09 Marnik - Up & Down",
        "OW01D10 MSI - Shut me up Full Song",
        "OW01E01 BanYa feat. CYO Style - Sorceress Virus",
        "OW01E02 BanYa feat. CYO Style - Extravaganza Battle",
        "OW01E03 SharaX - Mad Mew Mew",
        "OW01E04 MiatriSs - Mad Mew Mew",
        "OW01E05 Charlie Puth - Betty Boop (Blan Kato RMX)",
        "OW01F01 MSI - Stupid mf",
        "OW01F02 Frums - Credits"
    ],
    "991-MOESTEP": [
        "ASTERICK WAR -Brand new World by Shiena Nishizawa",
        "ASTERICK WAR-words of love by Chisuga Haruka",
        "Air Gear OP-chain by Back-On",
        "BEELZEBUB END 5-Shoujo Traveller by 9nine",
        "BLACK BULLET -Black Bullet by fripSide",
        "BLACK CLOVER- black catcher by vickeblanka",
        "BLACK CLOVER- right now by empire",
        "BLENDS S-Bon Appetit S",
        "BOKU NO HERO ACADEMIA-Koukai no Uta by Sayuri",
        "BOKU NO HERO ACADEMIA-polaris by blue encount",
        "Beatstar -Wild Side by ALI",
        "C³-endless story by yukari tamura",
        "DARWINS GAME- chain by asca",
        "DOROHEDORO-Welcome to Chaos by know name",
        "DUMBBELL- onegai muscle by AI FAIROUZ & KAITO",
        "Dr. Stone OP-Good Morning World! by BURNOUT SYNDROMES",
        "GIVEN OP-Kizuato by centimillimental",
        "GOBLIN SLAYER-Rightfully  by Mili",
        "Gleipnir -alternate by Helical",
        "HENSUKI-daisuki by Oohashi Ayaka",
        "HIGURASHI GOU-I believe what you said by Asaka",
        "HIGURASHI-Naraku No Hana by Eiko Shimamiya",
        "HITMAN REBORN-STAND UP! by Lead",
        "Hibikase by reol",
        "ID INVADED-Mr. Fixer by sou",
        "IN SPECTRE -Mononoke in the Fiction by Uso to Chameleon",
        "K-ON2-go go maniac! by Ho-Kago Tea Time",
        "KANOJO OKARASHIMASU - Centimeter by the peggies",
        "KANOJO OKARASHIMASU - First Drop by Halca",
        "KIMETSU NO YAIBA  My First Story by Reviver",
        "KIMETSU NO YAIBA-gurenge by lisa",
        "Kamisama ni Natta Hi- kimi to iu shinwa by jun maeda x nagi yanagi",
        "LOVE LIVE- PSYCHIC FIRE (short)",
        "MAHOUKA KOUKOU NO RETTOUSEI S2-  Howling by asca",
        "MAOU GAKUIN-Hamidashimono by kusonoki tomori",
        "MAOU GAKUIN-Seikai Fuseikai by CIVILIAN",
        "MONOGATARI ninja re bang bang by kyara no pamyu pamyu",
        "Mairimashita! Iruma kun- Magical babyrinth by kimi da pump",
        "Maniacal Degree by (Alstroemeria Records)",
        "Mob Psycho 100 II -99.9 by sajou no hana",
        "Mob Psycho 100-99 by MOB CHOIR",
        "Munou na Nana-Broken Sky by Miyu Tomita",
        "NISEKOI-Recover Decoration by Hanazawa Kana",
        "NISEKOI2-step by claris",
        "ONEGAI TEACHER-Shooting Star by KOTOKO",
        "OWARI NO SERAPH-X.U. by SawanoHiroyuki",
        "RAKUDAI KISHI NO CALVARY- Identity by Mikio Sakai",
        "REZERO Season 1- Paradisus Paradoxum by MYTH&ROID",
        "REZERO Season 1- Redo by Konomi Suzuki",
        "REZERO Season 1-STYX HELIX by MYTH&ROID",
        "REZERO Season 1-theater D by MYTH&ROID",
        "REZERO Season 2 -  Memento by nonoc",
        "REZERO Season 2 -  Realize by Konomi Suzuki",
        "ROKUDENASHI MAJUTSU-blow out by Suzuki Konomi",
        "RUNWAY DE WARATTE-lion by Ami Sakaguchi",
        "Resonant World-Fairy Fencer",
        "SETON GAKUEN-Gakuen Soukan Zoo by Ryouri-bu",
        "SHAKUGAN NO SHANA II-Sociometry by kotoko",
        "SHAKUGAN NO SHANA II-blaze by kotoko",
        "SHAKUGAN NO SHANA II-joint by mami kawada",
        "SHAKUGAN NO SHANA III-light my fire by kotoko",
        "SHAKUGAN NO SHANA III-serment by mami kawada",
        "SHAKUGAN NO SHANA S-Prophecy by Kawada Mami",
        "SHAKUGAN NO SHANA-Hishoku no Sora by mami kawada",
        "SHAKUGAN NO SHANA-being ny kotoko",
        "SHAMAN KING -Over Soul by megumin",
        "SHINGEKI NO KYOJIN-Guren no Yumiya by Linked Horizon",
        "SHINGEKI NO KYOJIN-Shinzou Wo Sasageyo by  Linked Horizon",
        "SHIRONEKO PROJECT ZERO CHRONICLE-balance libra by Takanori Nishikawa+ASCA",
        "TO ARU KAGAKU NO ACCELERATOR -Shadow is the Light by THE SIXTH LIE",
        "TO ARU KAGAKU NO RAILGUN OP2-Level 5 Judgelight by fripside",
        "TO ARU KAGAKU NO RAILGUN OVA - fripSide - Future Gazer",
        "TO ARU KAGAKU NO RAILGUN S-Sisters noise by fripside",
        "TO ARU KAGAKU NO RAILGUN S-eternal reality by fripside",
        "TO ARU KAGAKU NO RAILGUN T- final phase by fripside",
        "TO ARU KAGAKU NO RAILGUN- Only my Railgun by fripside",
        "TO ARU KAGAKU NO RAILGUN- dual existence by fripside",
        "TO ARU MAJUTSU INDEX 2 - Magic world by maon kurosaki",
        "TO ARU MAJUTSU NO INDEX  OP2-masterpiece by mami kawada",
        "TO ARU MAJUTSU NO INDEX 3- gravitation by mami kawada",
        "TO ARU MAJUTSU NO INDEX- psi missing",
        "TO ARU MAJUTUS NO INDEX 2-  No buts! by mami kawada",
        "TSUGU TSUGUMOMO-Kaze Fukeba Tsukiyo no Hate ni by AOP",
        "Tejina-senpai -FANTASTIC ILLUSION by i Ris",
        "The God of High School - Contradiction by feat. Tyler Carter",
        "VOCALOID- Spectrum",
        "WATTAMOTE- Do Kangaetemo Watashi wa Warukunai",
        "Watashi Nouryoku wa Heikinchi de tte Itta yo ne! -Smile Skill  Suki Skill by Akaki Chikai",
        "ZFULL01-Kawakiwo ameku by minami",
        "ZFULL02-Paradisus Paradoxum",
        "ZOMBIELAND SAGA-Temptation From Hell by Jun Suyama",
        "assassins pride-share the light by run girl run",
        "enen no shouboutai 2- spark again by Aimer",
        "jinchou yuusha- tit for tat by MYTH & ROID",
        "ore wo suki -papapa by saitou shuka",
        "tonikaku Kawaii- koi no uta by tsukasa tsukuyomi",
    ],
    "992-OmegaSteps": [
        "AmamoriP - Keep On",
        "BanYa - Solitary1.5",
        "Beautiful Day ~ V-3",
        "Boom Kitty - Gun n' Bass pt. 2 [Gun Sounds]",
        "Esto se va a descontrolar",
        "Family Farce ~ TSUHSUIXAMUSH",
        "Fuse ~ Titancube",
        "GHOSTEMANE ~ Mercury",
        "GRGE  How to Frenchcore",
        "Megalovania ~ [Pump]",
        "Miquiztli_Lerash Hell",
        "Miracle_5ymphoX",
        "Monsdeath - 150's BPM RemiX",
        "ParaganX9 - ChaozJapan Remix",
        "Paranoia Max Unlimited",
        "Paul Bazooka - Don't Die",
        "Paul Bazooka - Supa.MAX",
        "Running in the 90's",
        "SHK - DeathMoon",
        "Sanxion7 - LastDay Alive",
        "Shadow Fall - The Light That Blinds",
        "WaveRacer - Introooo"
    ],
    "993-OmegaSteps 2": [
        "Anubis - Banzai",
        "BanYa - Phantom Intermezzo",
        "Blend Slipknot",
        "Case & Point - Error Code",
        "Cleaner - DOIN",
        "CoffinDance Vs Vitas",
        "Doom - Doom's Gate",
        "Fascination MAXX",
        "Forgotten Tales - FairyTales",
        "Ghost - CIRICE",
        "K0i - Otra vez reprobé",
        "Kyary Pamyu Pamyu - Fashion Monster",
        "PARANOiA MEGAMIX",
        "Plastilina Mosh . Millionaire",
        "Raining Blood",
        "SOSO - Crazy Drive",
        "Sid Sound - Butterfly",
        "Strange Meat Pie - (K)now_NAME",
        "We Goin´Fly2",
        "Wiwek Ft. Keno - Double Dribble"
    ],
    "994-NIGHTMARE": [
        "3.FOOT EATER MIX 3 - Mago de Oz",
        "5.FOOT EATER MIX 5 - Helloween",
        "6.FOOT EATER MIX 6 - Stratovarius",
        "Anhedonia - A_hisa",
        "Entity - Lolistyle Grabbers",
        "PARANOiA MEGAMIX",
        "Psytrance Megamix  - Dog Fire",
        "Sherpas Paradox",
        "USAO ULTIMATE HYPER MEGA MIX - Usao"
    ],
    "995-DOG FIRE S3RL": [
        "01 INTRO MIX",
        "02 INTRO MIX",
        "03 INTRO MIX",
        "04 INTRO MIX  S3RL",
        "3 To The Floor  S3RL",
        "Addict  S3RL",
        "All That I Need   S3RL feat Kayliana  MC Riddle",
        "And Im Like - S3RL Outforce  Hartshorn",
        "Avaline - S3RL  Triple Zero ft Lindsey Marie",
        "BFF   S3RL",
        "Bass Slut  S3RL",
        "Be My Game Boy   Yurino  ft S3RL",
        "Beat all the Odds   S3RL ft Kitty & Lovely",
        "Berserk   S3RL ft Iceman",
        "Can t Control My Body   S3RL",
        "Catchit   S3RL",
        "Cherry Pop   S3RL feat Gl!tch",
        "Chillcore   S3RL feat Lexi",
        "Classics MashUp  S3RL",
        "Classics Mashup 2  S3RL",
        "Click Bait   S3RL feat Gl!tch",
        "DJ Whore   S3RL feat Tamika",
        "Da De Da S3RL",
        "Dance More   S3RL ft Ella",
        "Dopamine   S3RL ft Sara",
        "Earth Bb   S3RL ft Lexi",
        "Electric Sky 2016   S3RL feat Krystal",
        "Electronic Simpsons Music - S3RL  Radio Gosha",
        "Escape   S3RL feat Emi",
        "Everybody Wants To Be A DJ (S3RL Stylecore Remix)  S3RL & Synthwulf",
        "Fan Service - S3RL",
        "Feel The Melody  S3RL Ft Sara",
        "Feels Like Heaven   S3RL feat MoiMinnie",
        "Final Boss Absolutely Presents  S3RL",
        "Fire   S3RL ft Harri Rush & Krystal",
        "Flame Princess  S3RL feat Krystal",
        "Forever by S3rl",
        "Friendzoned   S3RL feat Mixie Moon",
        "Generic Holiday Song  S3RL ft  Sara",
        "Go Insane   S3RL feat MC Offside",
        "Heaven (S3RL ft Tamika Remix)   DJ Sammy",
        "Hentai  S3RL",
        "Hentai Service - S3RL Ft DGF",
        "I Wanna Stay - S3RL & Rob IYF ft Krystal",
        "I Will Be Yours  S3RL Ft Tamika",
        "I Will Pick You Up - S3RL feat Tamika",
        "Ill See You Again - S3RL feat Chi Chi",
        "Inspiration    S3RL",
        "It Went  S3RL Ft Tamika",
        "Its This Again   S3RL ft Jamie Rose",
        "Jaded AF   S3RL feat ChiyoKo & MC Riddle",
        "Kamehameha   S3RL feat j0hnny",
        "Light Of My Life  - S3RL",
        "Like This   S3RL feat Krystal & Slendy",
        "Line of Blow  S3RL Ft J Bigga",
        "MTC   S3RL",
        "MTC (Delusion  AoS Remix)  S3RL",
        "MTC (Different Heaven Remix) - S3RL",
        "MTC Saga - S3RL & Radio Gosha",
        "MTC Saga Final Chapter   S3RL ft Radio Gosha",
        "Marceline the Vampire Queen - S3RL feat. Sara",
        "Misleading Title   S3RL Feat DEFI BRILATOR",
        "Music is my Sour   S3RL ft Mixie Moon",
        "My Girlfriend is a Raver   S3RL x LIDA",
        "Nasty   S3RL  5H4RK80Y ft Thylie",
        "Neon Genesis  S3RL",
        "Neon Genesis (Pulse Remix) - S3RL",
        "Now That I've Found You - S3RL ft Déja",
        "Oh Oh Oh Sexy Vampire (S3RL vs Justin B remix) - Fright Range",
        "Over the Rainbow  S3RL ft Sara",
        "Pika Girl - S3RL",
        "Planet Rave -  S3RL ft Renee & Slendy",
        "Predictable Rave Song   S3RL ft Tamika",
        "Princess Bubblegum - S3RL ft Yuki",
        "Pump Up the Jams   S3RL & Zero2",
        "Punch The Gas  Brisk & S3RL",
        "R4V3 B0Y - S3RL feat Krystal",
        "Rainbow Girl   S3RL ft Tamika",
        "Ravers MashUp - S3RL",
        "Scary Movie - S3RL",
        "Silicon XX  - S3RL ft Nikolett",
        "Sky Rocket  S3RL ft Sara",
        "Speechless   S3RL",
        "Spoiler Alert   S3RL feat DEFI BRILATOR",
        "Spoiler Movie Pop Mashup  S3RL & Dog Fire",
        "SummerBass   S3RL feat  Tamika",
        "Techno Kitty S3RL Ft Sara",
        "The Bass & The Melody   S3RL",
        "The Perfect Rave - S3RL ft Krystal",
        "Through the Years (2018)   S3RL & Zero-2 ft Yurino",
        "Time Machine M Procjet Ft Krystal",
        "Toxic 2016   S3RL Ft Sara",
        "Untouchable   S3RL ft Sara  LIDA",
        "Waifu   S3RL & Alaguan ft Lexi",
        "Wanna Fight Huh  S3RL",
        "Well That Was Awkward - S3RL",
        "When Im There   S3RL feat Nikolett",
        "When You Are My Avaline  S3RL Ft DOG FIRE",
        "Where Did You Go   S3RL feat Charlotte",
        "Whirlwind   S3RL feat Krystal",
        "Will to be - S3RL feat. Sara",
        "You Are Mine   S3RL ft Kayliana"
    ],
    "996-OmegaSteps 3": [
        "Beatdown",
        "Billx - Smash",
        "Brutal",
        "CAPTAIN JACK (GRANDALE REMIX) - CAPTAIN JACK",
        "Charles Bronson",
        "Cuphead - Botanic Panic",
        "Don_t Touch The Kore (S3RL Remix)",
        "ESCAPE - D_AAN",
        "El esqueleto - victimas del doctor cerebro",
        "Falling Up",
        "G52 - Desperation",
        "HyunN ft. Ms Valentine - Cross+Fate",
        "Last Card",
        "Machine Rhythm",
        "Mandragora Skrillex Remix",
        "Master Of Puppets - Metallica",
        "Moonlight (Sonata 3rd Movt Cranky Mix)",
        "OMEGA",
        "Omega R - MAX SBY -428-",
        "Paul Bazooka - DrunkenStein",
        "Plus Danshi",
        "Prreo HP",
        "R4U",
        "Song That Might Play When You Fight Sans",
        "Sound Chimera",
        "Storia - Xi vs Sakuzyo",
        "THE WORLD REVOLVING",
        "Tatsh - Xepher",
        "XI - Blue Zenith",
        "[Full Song] Baroque Virus",
        "[Full Song] Leaf - Aleph-0",
        "[Full Song] R4U",
        "[Full Song] Synthwulf - POINT ZERO TWO",
        "[Short Cut] Come To Me"
    ]
}